name: Node js test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version in nvmrc and set to output to env variable
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc | tr -cd [:digit:].)" >> "$GITHUB_ENV"
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: install node modules
        run: pnpm install
      - name: Check format
        run: pnpm run format:check
      - name: Check linting
        env:
          SKIP_ENV_VALIDATION: 1
        run: pnpm run lint
